// English Restaurant Lesson Data (95 lines)
export const EN_RESTAURANT_LINES = [
  { speaker: 1, segment: 'WELCOME', text: "Hello and welcome to today's lesson on dining at a restaurant!" },
  { speaker: 1, segment: 'WELCOME', text: "Today, we'll learn some important vocabulary and phrases you can use when you eat out." },
  { speaker: 1, segment: 'WELCOME', text: "Are you ready to dive into the world of restaurants?" },
  { speaker: 1, segment: 'WELCOME', text: "Let's start by exploring some key words and phrases related to dining!" },
  { speaker: 1, segment: 'WELCOME', text: "Whether you're ordering food, asking questions, or making reservations, we've got you covered." },
  { speaker: 1, segment: 'WELCOME', text: "Don't worry if you don't know everything right away; practice makes perfect!" },
  { speaker: 1, segment: 'WELCOME', text: "By the end of this lesson, you'll feel more confident when dining out." },
  { speaker: 1, segment: 'WELCOME', text: "So, let's get started and have some fun learning together!" },
  { speaker: 2, segment: 'VOCAB', text: "First, let's go over some essential restaurant vocabulary." },
  { speaker: 2, segment: 'VOCAB', text: "Menu - A list of food and drinks available at the restaurant" },
  { speaker: 2, segment: 'VOCAB', text: "Reservation - An arrangement to have a table set aside for you at a specific time" },
  { speaker: 2, segment: 'VOCAB', text: "Waiter/Waitress - The person who takes your order and serves your food" },
  { speaker: 2, segment: 'VOCAB', text: "Bill - The statement of the money you owe for your meal" },
  { speaker: 2, segment: 'VOCAB', text: "Tip - Extra money given to the waiter for good service" },
  { speaker: 2, segment: 'VOCAB', text: "Appetizer - A small dish served before the main course" },
  { speaker: 2, segment: 'VOCAB', text: "Main course - The primary dish in a meal" },
  { speaker: 2, segment: 'VOCAB', text: "Dessert - A sweet course served at the end of a meal" },
  { speaker: 2, segment: 'VOCAB', text: "Special - A dish that is featured for a limited time at a restaurant" },
  { speaker: 2, segment: 'VOCAB', text: "Takeout - Food that you order to eat elsewhere" },
  { speaker: 2, segment: 'VOCAB', text: "Buffet - A style of dining where guests serve themselves from a variety of dishes" },
  { speaker: 2, segment: 'VOCAB', text: "Chef - The person who cooks food in the restaurant" },
  { speaker: 2, segment: 'VOCAB', text: "Allergy - A medical condition that can cause a severe reaction to certain foods" },
  { speaker: 2, segment: 'VOCAB', text: "Beverage - Any drink, such as water, soda, or wine, served at the restaurant" },
  { speaker: 1, segment: 'SLOW', text: "Now, let's practice a slow dialogue to help you understand the phrases better." },
  { speaker: 2, segment: 'SLOW', text: "Good evening! How many people are in your party?" },
  { speaker: 1, segment: 'SLOW', text: "We have four people." },
  { speaker: 2, segment: 'SLOW', text: "Great! Do you have a reservation?" },
  { speaker: 1, segment: 'SLOW', text: "Yes, we do. It's under the name Smith." },
  { speaker: 2, segment: 'SLOW', text: "Perfect! Right this way, please." },
  { speaker: 1, segment: 'SLOW', text: "Thank you!" },
  { speaker: 2, segment: 'SLOW', text: "Here are your menus. Can I get you something to drink?" },
  { speaker: 1, segment: 'SLOW', text: "Yes, I would like some water, please." },
  { speaker: 2, segment: 'SLOW', text: "And for you?" },
  { speaker: 1, segment: 'SLOW', text: "I'll have a soda." },
  { speaker: 2, segment: 'SLOW', text: "Alright, I will be back with your drinks shortly." },
  { speaker: 1, segment: 'SLOW', text: "Thank you!" },
  { speaker: 2, segment: 'SLOW', text: "You're welcome!" },
  { speaker: 1, segment: 'BREAKDOWN', text: "Let's break down those phrases a bit." },
  { speaker: 2, segment: 'BREAKDOWN', text: "'Good evening!' is a polite way to greet someone at dinner time." },
  { speaker: 1, segment: 'BREAKDOWN', text: "'How many people are in your party?' asks how many guests are dining together." },
  { speaker: 2, segment: 'BREAKDOWN', text: "'Do you have a reservation?' checks if you booked a table in advance." },
  { speaker: 1, segment: 'BREAKDOWN', text: "'It's under the name Smith' means that you made a reservation using that name." },
  { speaker: 2, segment: 'BREAKDOWN', text: "'Right this way, please' is a polite invitation to follow someone to your table." },
  { speaker: 1, segment: 'BREAKDOWN', text: "'Can I get you something to drink?' is how the waiter offers beverages to the customers." },
  { speaker: 2, segment: 'BREAKDOWN', text: "'I'll have a soda' indicates your choice of drink." },
  { speaker: 1, segment: 'BREAKDOWN', text: "'I will be back with your drinks shortly' assures you that the waiter will return soon." },
  { speaker: 2, segment: 'NATURAL', text: "Good evening! Welcome to our restaurant. How can I assist you tonight?" },
  { speaker: 1, segment: 'NATURAL', text: "Hi! We have a reservation for four under the name Smith." },
  { speaker: 2, segment: 'NATURAL', text: "Ah, yes! Right this way. Here are your menus." },
  { speaker: 1, segment: 'NATURAL', text: "Thank you! Could you tell us about today's specials?" },
  { speaker: 2, segment: 'NATURAL', text: "Absolutely! Today we have a grilled salmon with asparagus and a creamy risotto." },
  { speaker: 1, segment: 'NATURAL', text: "That sounds delicious! I think I'll try the salmon." },
  { speaker: 2, segment: 'NATURAL', text: "Excellent choice! And for you?" },
  { speaker: 1, segment: 'NATURAL', text: "I will have the risotto, please." },
  { speaker: 2, segment: 'NATURAL', text: "Perfect! Would you like to start with an appetizer?" },
  { speaker: 1, segment: 'NATURAL', text: "Yes, let's have the garlic bread for the table." },
  { speaker: 2, segment: 'NATURAL', text: "Great choice! I'll put that in for you. What would you like to drink?" },
  { speaker: 1, segment: 'NATURAL', text: "I'll have a glass of white wine." },
  { speaker: 2, segment: 'NATURAL', text: "Very nice! And for you?" },
  { speaker: 1, segment: 'NATURAL', text: "Just water for me, thanks." },
  { speaker: 2, segment: 'NATURAL', text: "Sure thing! I'll be right back with your drinks and the appetizer." },
  { speaker: 1, segment: 'NATURAL', text: "Thank you!" },
  { speaker: 2, segment: 'NATURAL', text: "You're welcome! Enjoy your evening." },
  { speaker: 1, segment: 'NATURAL', text: "This place has a lovely atmosphere." },
  { speaker: 2, segment: 'NATURAL', text: "Yes, we strive to make it cozy and inviting for our guests." },
  { speaker: 1, segment: 'NATURAL', text: "How long have you been working here?" },
  { speaker: 2, segment: 'NATURAL', text: "I've been here for about three years now. It's a great environment." },
  { speaker: 1, segment: 'NATURAL', text: "That's awesome! What's your favorite dish on the menu?" },
  { speaker: 2, segment: 'NATURAL', text: "Personally, I love the steak; it's grilled to perfection!" },
  { speaker: 1, segment: 'NATURAL', text: "I'll have to try that next time!" },
  { speaker: 2, segment: 'NATURAL', text: "Definitely! I'll be back shortly with your drinks and the garlic bread." },
  { speaker: 2, segment: 'QUIZ', text: "Now, let's do a short quiz to reinforce what you've learned." },
  { speaker: 1, segment: 'QUIZ', text: "What do you call the list of food and drinks at a restaurant?" },
  { speaker: 2, segment: 'QUIZ', text: "Answer: Menu." },
  { speaker: 1, segment: 'QUIZ', text: "Who takes your order?" },
  { speaker: 2, segment: 'QUIZ', text: "Answer: Waiter/Waitress." },
  { speaker: 1, segment: 'QUIZ', text: "What is the extra money you give for good service?" },
  { speaker: 2, segment: 'QUIZ', text: "Answer: Tip." },
  { speaker: 1, segment: 'QUIZ', text: "What is the primary dish in a meal called?" },
  { speaker: 2, segment: 'QUIZ', text: "Answer: Main course." },
  { speaker: 1, segment: 'QUIZ', text: "What do you call food ordered to eat elsewhere?" },
  { speaker: 2, segment: 'QUIZ', text: "Answer: Takeout." },
  { speaker: 1, segment: 'QUIZ', text: "What do you call a booking made for a table?" },
  { speaker: 2, segment: 'QUIZ', text: "Answer: Reservation." },
  { speaker: 1, segment: 'QUIZ', text: "What is a small dish served before the main course?" },
  { speaker: 2, segment: 'QUIZ', text: "Answer: Appetizer." },
  { speaker: 1, segment: 'QUIZ', text: "What do you call a style of dining where guests serve themselves?" },
  { speaker: 2, segment: 'QUIZ', text: "Answer: Buffet." },
  { speaker: 1, segment: 'CULTURAL', text: "Finally, let's discuss some cultural notes about dining in English-speaking countries." },
  { speaker: 2, segment: 'CULTURAL', text: "Tipping is customary in many restaurants; around 15-20% is standard." },
  { speaker: 1, segment: 'CULTURAL', text: "In some cultures, it's common to have a drink before the meal, often at the bar." },
  { speaker: 2, segment: 'CULTURAL', text: "Reservations are recommended, especially on weekends or at popular restaurants." },
  { speaker: 1, segment: 'CULTURAL', text: "It's polite to wait for everyone at the table to be served before starting to eat." },
  { speaker: 2, segment: 'CULTURAL', text: "Asking about food allergies is important and should always be done before ordering." },
];
